services:

  db:
    image: postgres:14
    container_name: deckgame_db
    environment:
      POSTGRES_DB: deckdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - deckgame-net

  app:
    build: .
    container_name: deckgame_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - deckgame-net

networks:
  deckgame-net: